# Execute API tests in tests/ with server.py running locally

name: Local API Tests

on: 
  push:
    paths: 
      - server.py
      - requirements.txt
      - compendium/**/*
      - src/*
  workflow_dispatch:

jobs:
  main:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [15.x]
          python-version: ["3.9"]
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: BSFishy/pip-action@v1
        with: 
          requirements: requirements.txt
      - name: Start API server
        run: |
            sh setup_versioning.sh
            python3 server.py ${{ secrets.RS2_TOKEN }} &
      - name: Install dependencies
        run: |
            cd tests
            npm i 
            sudo npm i -g mocha 
            sudo npm i -g ts-node
            sudo npm i typescript
      - name: Execute tests
        run: |
            cd tests
            env URL="http://127.0.0.1:5000/api/v2" mocha test/api.ts -r ts-node/register